---
- hosts: PowerEdge
  connection: local
  gather_facts: False

  tasks:

  - name: throw a safety switch
    set_fact:
      check_yourself: "i will"

  - name: get server profile volume
    dellemc.openmanage.idrac_server_config_profile:
      validate_certs: false
      idrac_ip: "{{ obm_ip }}"
      idrac_user: "{{ obm_user }}"
      idrac_password: "{{ obm_password }}"
      share_name: "/opt/nobm/data"
      scp_components:
        - BIOS
      scp_file: {{ inventory_hostname }}-profile.json
    when: check_yourself == "i did"
